# Generated by Django 4.2.1 on 2023-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('seller_username', models.CharField(max_length=200)),
            ],
        ),
    ]
