# Generated by Django 4.2.1 on 2023-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0002_purchase_buyer_purchase_buyer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_no',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
