# Generated by Django 4.2.1 on 2023-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0003_purchase_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_no',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
